version: '3'
services:
  flask:
    #image: gokuldp/kasm-backend
    build: .
    container_name: remote-flask
    environment:
      APP_ENV: "prod"
      APP_DEBUG: "False"
      APP_PORT: 5000
      PYTHONUNBUFFERED: 1
      MONGODB_DATABASE: flaskdb
      MONGODB_USERNAME: flaskuser
      MONGODB_PASSWORD: mongoPass
      MONGODB_HOSTNAME: mongodb
      FLASK_DEBUG: "on"
    volumes:
      - ./app:/app
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 5000:5000
    networks:
      - frontend
      - backend
  mongodb:
    image: mongo:6.0.1
    container_name: remote_mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongoPass
      MONGO_INITDB_DATABASE: flaskdb
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    networks:
      - backend
  nginx:
    build: ./nginx/
    ports:
      - 80:80
    networks:
      - frontend
      - backend
      - containers


networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
  containers:
    name: "containers"
    external: true
